version: '3.8'

services:
  portfolio:
    build: .
    ports:
      - "3000:80"
    container_name: portfolio-dev
    restart: unless-stopped
    
  # Optional: Development with live reload
  dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
    container_name: portfolio-dev-server
    environment:
      - NODE_ENV=development